### ISSUE TITLE
EVAL doesn't seem to work.

### ISSUE THREAD

**Issue by adilbaig** [predis/predis#100]
I've tried to extend ScriptedCommand to run a small Lua script. I based my code on the example in README.md

```
$this->redis->getProfile()->defineCommand('deleteBatch', 'Stockopedia\DemoBundle\Command\DeleteBatch');

$this->redis->deleteBatch("{$batchId}:*");
```

The DeleteBatch Command is as follows 

```
class DeleteBatch extends ScriptedCommand
{
    public function getKeysCount()
    {
        return 1;
    }

    public function getScript()
    {
        return
<<<LUA
local some = redis.call('keys',ARGV[1]); 
for i,v in pairs(some) do 
    redis.call('DEL', v) 
end
LUA;
    }
}
```

On running this, i get the following exception

```
[Predis\ClientException]                  
  'eval' is not a registered Redis command
```

PS : I'm on redis_version:2.6.8

**Comment by ssuperczynski** [comment]
If anyone has still the problem with this issue, and using SncRedisBundle.
You can add correct profile version in `config.yml`:
```
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            options:
                profile: 2.6
```
