### ISSUE TITLE
Aggregate connections are not being removed in combination with own connection class

### ISSUE THREAD

**Issue by ostrolucky** [predis/predis#777]
**Describe the bug**
[snc_redis](https://github.com/snc/SncRedisBundle) has its own connection class `\Snc\RedisBundle\Client\Predis\Connection\ConnectionWrapper`. `\Predis\Connection\Aggregate\RedisCluster::remove` method apparently doesn't count with that and doesn't remove faulty connections

![image](https://user-images.githubusercontent.com/496233/174729378-830e63aa-1873-4152-a0ef-d103d8ee8b93.png)

**To Reproduce**

snc_redis.yaml config
```
snc_redis:
    clients:
        bl_domain:
            type: predis
            dsn: 
              - redis://127.0.0.1:9999 #purposefully wrong port
              - redis://127.0.0.1:6380
            options:
                cluster: redis
```

then run some redis query

**Expected behavior**
Predis should remove such connections as well, so that it can failover to next connection in pool.

**Versions (please complete the following information):**
 - Predis: 1.1.10
 - PHP 8.1.4
 - Redis Server 6.0.15
 - OS Debian 10
